services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  front:
    image: node
    working_dir: /var/app
    volumes:
      - ./front:/var/app
    ports:
      - "5000:5000"
    command: sleep infinity


  app1:
    image: golang
    working_dir: /var/app
    volumes:
      - ./back:/var/app
    command: go run ./main.go

  app2:
    image: golang
    working_dir: /var/app
    volumes:
      - ./back:/var/app
    command: go run ./main.go

  app3:
    image: golang
    working_dir: /var/app
    volumes:
      - ./back:/var/app
    command: go run ./main.go

  app4:
    image: golang
    working_dir: /var/app
    volumes:
      - ./back:/var/app
    command: go run ./main.go